# Cambiar a base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:pedidosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola para ver los datos en el navegador
spring.h2.console.enabled=true

# Puerto del microservicio
server.port=8081